version: '3'

services:
  express:
    container_name: server-express
    restart: always
    build:
      context: .
      dockerfile: docker/server.DockerFile
    volumes:
      - ./src:/app/src
    ports:
      - '4000:4000'
    links:
      - mongo:mongo
  mongo:
    container_name: server-mongodb
    restart: always
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
